cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    alice johnson:
      email: alice.johnson@example.com
      id: 3
      logged_in: false
      name: Alice Johnson
      password: $2b$12$QDra4rRFgO/Aat5V.PIViepSOoZV7U6Teg.JQ.FnLCwcqTo4fSzlu
      role: Student
    aske meineche:
      email: askemeineche@protonmail.com
      id: 1
      logged_in: false
      name: Aske Meineche
      password: $2b$12$QDra4rRFgO/Aat5V.PIViepSOoZV7U6Teg.JQ.FnLCwcqTo4fSzlu
      role: Student
    askemeineche:
      email: aske.osv@gmail.com
      id: 5
      logged_in: false
      name: AskeMeineche
      password: $2b$12$QDra4rRFgO/Aat5V.PIViepSOoZV7U6Teg.JQ.FnLCwcqTo4fSzlu
      role: Student
    bob brown:
      email: bob.brown@example.com
      id: 4
      logged_in: false
      name: Bob Brown
      password: $2b$12$QDra4rRFgO/Aat5V.PIViepSOoZV7U6Teg.JQ.FnLCwcqTo4fSzlu
      role: Educator
    jane:
      email: jane.smith@example.com
      id: 2
      logged_in: false
      name: Jane
      password: $2b$12$QDra4rRFgO/Aat5V.PIViepSOoZV7U6Teg.JQ.FnLCwcqTo4fSzlu
      role: Educator
    karl:
      email: karl@gmail.com
      github_user_name: karl
      id: !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args:
        - i8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        BwAAAAAAAAA=
      logged_in: false
      name: karl
      password: $2b$12$0.lagzrkCfjvNvl41lg3WuQPVP81BoIjFna46q8HmsWwOdmmp1V/S
      role: Student
    karls:
      email: karls@gmail.com
      id: 6
      logged_in: false
      name: karls
      password: $2b$12$OvGibEuXiuOW5fsWsAXe4.wb3A5k.54K9iBH18B.kpzxG1SWWdwfi
      role: Student
